### ISSUE TITLE
Transaction nonce question 

### ISSUE THREAD

**Issue by masterdxy** [mosaicnetworks/evm-babble#2]
Hello
if many transaction submitted to babble proxy , how to ensure the nonce of transaction is ordered ？ 
I send 50+ txs to evm_babble but it return nonce is too high or nonce is too low sometimes.

Expected reply ！

**Comment by arrivets** [comment]
Hello,
 
Which endpoint are you using to send the transactions?  `/rawtx` or `/tx` ?

**Comment by masterdxy** [comment]
I'm using `/tx` endpoint .

**Comment by masterdxy** [comment]
is there need a tx_pool  ?

**Comment by arrivets** [comment]
Possibly, but let's see if there is an easy solution first.

So there are two ways to manage the nonce:

1) Leave the `nonce` field empty in the RPC request. The EVM-Babble side will populate that field automatically based on the account's state.
2) Manage and specify the nonce yourself. This requires checking transaction receipts, incrementing the nonce correctly..etc.

With the `/tx` endpoint, it's easier to use the first method.

Which one are you using?

**Comment by masterdxy** [comment]
i'm using the first method. but,
if i send tx continuously, `*args.Nonce = state.GetNonce(args.From)` will fill an old nonce.
eg:
first tx fill nonce=0 , and added to []transactions, if it not be consensus, the state is also 0 now,
second tx will fill nonce=0 too ,because the block may not be commited for now, it will cause the problem.
For ethereum , the tx_pool will use managed_state to manage nonce for tx not executed that time.

**Comment by arrivets** [comment]
ah ok. Yes that makes sense.
I'll create an issue and try to address it as soon as possible. Feel free to make a pull request also :)
That being said, we are working on a new product called EVM-Lite which will be the replacement of EVM-Babble, and EVM-Babble will be deprecated soon. It was always a sort of prototype..
EVM-Lite will look much the same but with interchangeable consensus, and the first version will be open-sourced in the coming weeks.

**Comment by masterdxy** [comment]
Very expect for that !
