### ISSUE TITLE
The evm-babble memory usage too high 

### ISSUE THREAD

**Issue by junwei0117** [mosaicnetworks/evm-babble#3]
### Description :
After I started the demo, I found that the docker container memory usage is surprisingly high, but when it is idle for a period of time, the memory usage will decline (more detailed instructions below).

#### Docker container started
![](https://i.imgur.com/vvZCSb3.png)

Each **clinet** memory usage is  about **270MB**.

#### Idle for 10 minutes
![](https://i.imgur.com/CNmKiDd.png)

Each **clinet** memory usage is decline to about **15MB**.

#### After deployed a smart contract
![](https://i.imgur.com/vniaWcD.png)

Each **client** memory usage rise to  about **17MB**.
Each **node** memory usage rise to  about **72MB**.

#### Idle for 10 minutes
![](https://i.imgur.com/0lfy33Y.png)

Each **node** memory usage decline to about **31MB**

---

|          | Started   |  Idle for 10 minutes |Deployed a smart contract|Idle for 10 minutes|
| -------- | --------  | -------- | -------- | -------- |
| Babble (node)   | 270 MB    | 15 MB    | 17 MB    | 16 MB    |
| EVM-Babble (client)     | 15 MB     | 10 MB    | 72 MB    | 31 MB    |

### Question :
1. What is the reason for this?
2. If docker container has been interacting with clients for a long time, such high memory usage would cause some problems, what solution would you recommand?

**Comment by arrivets** [comment]
Hi,
Thanks a lot for the very detailed message.

Just to clarify in the table (maybe it's a typo), Babble is the node, and EVM-Babble is the client.

I dont understand why evm-babble is using all that memory at the beginning; all it's supposed to be doing at that stage is to initialize the state Trie and create some accounts.

I will look into it.

**Comment by junwei0117** [comment]
Thank you for reminding me,
If you have any progress, please let me know.
